name: Upload to S3
run-name: S3 Upload

on:
  push:
    branches: [ "main" ]
     
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Upload to S3
        run: aws s3 sync $GITHUB_WORKSPACE s3://cloudfront-deploy-bucket-memojideveloper
  
